# Generated by Django 5.1.6 on 2025-02-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digimon',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.RemoveField(
            model_name='digimon',
            name='user',
        ),
        migrations.AddField(
            model_name='digimon',
            name='user',
            field=models.ManyToManyField(to='main_app.digimon'),
        ),
    ]
