# Generated by Django 5.1.6 on 2025-02-18 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_digimon_name_remove_digimon_user_digimon_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='digimon',
            name='user',
            field=models.ManyToManyField(related_name='digimon', to=settings.AUTH_USER_MODEL),
        ),
    ]
