# Generated by Django 5.1.6 on 2025-02-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_digimon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digimon',
            name='img',
            field=models.CharField(max_length=260),
        ),
        migrations.AlterField(
            model_name='digimon',
            name='level',
            field=models.TextField(max_length=260),
        ),
        migrations.AlterField(
            model_name='digimon',
            name='name',
            field=models.CharField(max_length=260, unique=True),
        ),
    ]
